### ISSUE TITLE
Add additional abstraction layers to decouple code

### ISSUE THREAD

**Issue by wkozyra95** [kasia-rusiecka/ComptonCamera6#5]
I omitted all elements that were obvious or not relevant.
Disclaimer for those who know UML, I'm aware that it's not 100% correct class diagram but it's easier to show proposed structure that way.

![untitled diagram](https://user-images.githubusercontent.com/9753141/48648242-e8155300-e9ee-11e8-9e31-21b3564d5736.png)
```cpp
int main(int argc, char *argv[]) {
    Mask* mask = gGenerateMURAMask(n, maskSizeX, maskSizeY, maskZValue);
    mask.setMaterial(gMaterial); // or antoher constructor arguent
    Detector* detector = new Detector(xResolution, yResolution, xSize, ySize);
    Source* source = gGenerateRandomSource(zPosition, xSize, ySize));
    // or
    Source* source = new FuncSource(zPosition, [](int x, int y){ return x*x+y*y} );

    CMSimulation simulation(source, mask, detector);
    simulation.run();
    simulation.save(filename);
    return 0;
}
Mask2D* gGenerateMURAMask(int n, float maskSizeX, float maskSizeY, float maskZValue);
SegmentedSource* gGenerateRandomSource(zPosition, xSize, ySize);
```

### Geometry
I think that a safe assumption is that mask will be always parallel to the detector, so we can define geometry in terms of values along one axis only. Also, we can assume that mask, source, and detector are positioned in x,y plane (currently z,y plane is used, but histograms have values described by x and y which is a bit confusing). For any angle related changes in the future we can just manipulate source logic.

### Mask
```cpp
bool Mask::processParticle(Track* track)
```
returns info whether particle was absorbed or not, track argument is modified(if absorbed energy ==0 else position changed to a position where the particle is leaving mask.
A similar interface could be implemented for scatterer in Compton version.
During construction we define material(a small class that calculates probability o absorption)
Example usage
```cpp
const Material gBlackBodyMaterial([](int distance) { return true; });
Material* linearAbsorptionMaterial(float a) { return new Material(](int distance) { return a*distance > 1; })
```
### Simulation
Entire code for handling simulation would look like that.
```cpp
Track* particle = fSource.generateEvent();
bool isAbsored = fMask.processParticle(particle);
if (isAbsorbed) return;
fDetector.scoreParticle(particle);
```

Each case where I use global variable could be replaced with static method or variable.

We should choose whether to use constructor args or setters to setup object state. For the current proposition, I think constructors are a bit cleaner solution. Using setters would be better if we would want to support more complex situations e.g. center of mask and center of the detector are not aligned
  
  
Few small sugestions (not very crucial, but can be done during this refactor)
- rename Track to Particle or Trace
- changing cout to some logger
- some abstraction that minimizes code used to save class to file (moving as much code as possible to separate class)

**Comment by slsyy** [comment]
zle sa strzalki

**Comment by wkozyra95** [comment]
Refactor finished only partially, using geant 4 simulations is next step so refactor of simulation code has lower priority.
Closing for now.
